- name: Install example of a Shibboleth Service Provider for UbuntuNet Alliance
  hosts: sp
  become: True

  vars_files:
    - group_vars/secrets.yml

  roles:
    - apache
    - shibboleth
    - newrelic